require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 140

Style/RedundantFileExtensionInRequire:
  Enabled: false
