require_relative './models/player.rb'
require_relative './models/team.rb'
require_relative './models/match.rb'
require_relative './models/performance_goal.rb'
require_relative './models/player_performance.rb'
require_relative './seed.rb'
